import { 
  TrendingUp, Cpu, Activity, Clock, ShieldCheck
} from 'lucide-react';

export default function AnalyticsTab() {
  const topAgents = [
    { name: 'Crane Zone Safety Agent', efficacy: '92%', change: '-12% Zone Violations', type: 'Security' },
    { name: 'PPE Compliance Agent', efficacy: '89%', change: '-42% PPE Deviations', type: 'Safety' },
    { name: 'Haul Road Monitoring Agent', efficacy: '84%', change: '-5% Speed Deviations', type: 'Operations' },
    { name: 'Workshop Safety Agent', efficacy: '81%', change: '-8% Hazard Triggers', type: 'Safety' }
  ];

  const highestRiskAreas = [
    { zone: 'Sector A Quarry Incline', score: 'High Risk (Level 4)', incidentsCount: 14 },
    { zone: 'Crane Loading Zone B', score: 'Medium Risk (Level 3)', incidentsCount: 8 },
    { zone: 'Stockpile North Conveyor', score: 'Low Risk (Level 1)', incidentsCount: 2 }
  ];

  return (
    <div className="flex flex-col gap-6 animate-fade-in flex-1">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-blue-950 flex items-center gap-2">
          <Activity className="text-blue-600" />
          Policy Intelligence Analytics
        </h2>
        <p className="text-xs text-slate-500 mt-1">Audit outcomes, coverage performance, and safety compliance improvements generated by active AI Agents.</p>
      </div>

      {/* Analytics Bento Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Policy Coverage */}
        <div className="bg-white p-5 rounded-xl border border-blue-50 shadow-sm flex flex-col justify-between">
          <div className="flex justify-between items-start">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Coverage Rate</span>
            <span className="p-1.5 bg-blue-50 text-blue-600 rounded-lg">
              <ShieldCheck size={16} />
            </span>
          </div>
          <div className="mt-4">
            <h3 className="text-2xl font-extrabold text-slate-900">91.4%</h3>
            <span className="text-xs text-slate-500">Active monitoring coverage</span>
          </div>
        </div>

        {/* Detection Accuracy */}
        <div className="bg-white p-5 rounded-xl border border-blue-50 shadow-sm flex flex-col justify-between">
          <div className="flex justify-between items-start">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Detection Accuracy</span>
            <span className="p-1.5 bg-blue-50 text-blue-600 rounded-lg">
              <Cpu size={16} />
            </span>
          </div>
          <div className="mt-4">
            <h3 className="text-2xl font-extrabold text-slate-900">98.2%</h3>
            <span className="text-xs text-slate-500">False Positive Rate &lt;1.8%</span>
          </div>
        </div>

        {/* Avg Response Time */}
        <div className="bg-white p-5 rounded-xl border border-blue-50 shadow-sm flex flex-col justify-between">
          <div className="flex justify-between items-start">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Response Time Reduction</span>
            <span className="p-1.5 bg-blue-50 text-blue-600 rounded-lg">
              <Clock size={16} />
            </span>
          </div>
          <div className="mt-4">
            <h3 className="text-2xl font-extrabold text-slate-900">-82%</h3>
            <span className="text-xs text-green-600 font-semibold flex items-center gap-0.5">
              <TrendingUp size={12} /> Avg response under 30s
            </span>
          </div>
        </div>

        {/* Safety Compliance Improvement */}
        <div className="bg-white p-5 rounded-xl border border-blue-50 shadow-sm flex flex-col justify-between">
          <div className="flex justify-between items-start">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Safety Compliance</span>
            <span className="p-1.5 bg-blue-50 text-blue-600 rounded-lg">
              <Activity size={16} />
            </span>
          </div>
          <div className="mt-4">
            <h3 className="text-2xl font-extrabold text-slate-900">+42%</h3>
            <span className="text-xs text-green-600 font-semibold">Incident frequency reduced</span>
          </div>
        </div>
      </div>

      {/* Main Charts & Breakdown Section */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Column: Agent Effectiveness Ranking */}
        <div className="lg:col-span-8 bg-white rounded-xl border border-blue-50 p-6 shadow-sm flex flex-col gap-4">
          <div className="pb-3 border-b border-slate-100 flex justify-between items-center">
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Agent Effectiveness Ranking</h3>
            <span className="text-xs text-slate-400 font-mono">Efficacy Rating</span>
          </div>

          <div className="flex flex-col gap-5 mt-2">
            {topAgents.map((v, idx) => {
              const widthPerc = v.efficacy;
              return (
                <div key={idx} className="flex flex-col gap-1.5">
                  <div className="flex justify-between text-xs font-semibold text-slate-700">
                    <span className="font-bold text-slate-800">{v.name}</span>
                    <span className="font-mono text-slate-500">Score: {v.efficacy} ({v.change})</span>
                  </div>
                  <div className="w-full bg-slate-100 rounded-full h-2 shadow-inner">
                    <div 
                      style={{ width: widthPerc }} 
                      className="bg-gradient-to-r from-blue-700 to-blue-500 h-2 rounded-full transition-all duration-500"
                    ></div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Business outcome insight block */}
          <div className="p-4 bg-blue-50/30 rounded-lg border border-blue-50 flex items-start gap-2.5 mt-4">
            <TrendingUp size={16} className="text-blue-600 shrink-0 mt-0.5" />
            <p className="text-xs text-slate-600 leading-relaxed">
              <strong>Efficacy Insight:</strong> The Crane Zone Safety Agent leads with <strong>92% Effectiveness</strong>, successfully reducing restricted access safety hazards through real-time geofence enforcement.
            </p>
          </div>
        </div>

        {/* Right Column: Safety Risk Distribution & High Risk Zones */}
        <div className="lg:col-span-4 flex flex-col gap-6">
          
          {/* Safety Risk Distribution Section (Revisi Minor 3) */}
          <div className="bg-white rounded-xl border border-blue-50 p-6 shadow-sm flex flex-col gap-4">
            <div className="pb-3 border-b border-slate-100">
              <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Safety Risk Distribution</h3>
              <p className="text-[10px] text-slate-400 mt-0.5">Risk load breakdown by zone sectors</p>
            </div>

            {/* Stacked Progress Bar */}
            <div className="w-full h-4 bg-slate-100 rounded-full flex overflow-hidden shadow-inner">
              <div style={{ width: '42%' }} className="bg-red-500 h-full" title="Crane Zone (42%)"></div>
              <div style={{ width: '28%' }} className="bg-orange-500 h-full" title="Crusher Area (28%)"></div>
              <div style={{ width: '17%' }} className="bg-yellow-500 h-full" title="Workshop (17%)"></div>
              <div style={{ width: '13%' }} className="bg-blue-500 h-full" title="Haul Road (13%)"></div>
            </div>

            <div className="flex flex-col gap-2.5 mt-1">
              <div className="flex justify-between items-center text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-sm bg-red-500 shrink-0"></span>
                  <span className="font-semibold text-slate-700">Crane Zone</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 text-[10px] font-bold px-1.5 py-0.5 bg-red-50 text-red-700 rounded border border-red-100 uppercase">High Risk</span>
                  <span className="font-bold text-slate-900">42%</span>
                </div>
              </div>

              <div className="flex justify-between items-center text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-sm bg-orange-500 shrink-0"></span>
                  <span className="font-semibold text-slate-700">Crusher Area</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 text-[10px] font-bold px-1.5 py-0.5 bg-orange-50 text-orange-700 rounded border border-orange-100 uppercase">Medium Risk</span>
                  <span className="font-bold text-slate-900">28%</span>
                </div>
              </div>

              <div className="flex justify-between items-center text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-sm bg-yellow-500 shrink-0"></span>
                  <span className="font-semibold text-slate-700">Workshop</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 text-[10px] font-bold px-1.5 py-0.5 bg-yellow-50 text-yellow-700 rounded border border-yellow-100 uppercase">Medium Risk</span>
                  <span className="font-bold text-slate-900">17%</span>
                </div>
              </div>

              <div className="flex justify-between items-center text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-sm bg-blue-500 shrink-0"></span>
                  <span className="font-semibold text-slate-700">Haul Road</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 text-[10px] font-bold px-1.5 py-0.5 bg-blue-50 text-blue-700 rounded border border-blue-100 uppercase">Low Risk</span>
                  <span className="font-bold text-slate-900">13%</span>
                </div>
              </div>
            </div>
          </div>

          {/* Highest Risk Zones list */}
          <div className="bg-white rounded-xl border border-blue-50 p-6 shadow-sm flex flex-col gap-4">
            <div className="pb-3 border-b border-slate-100">
              <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Highest Risk Zones</h3>
            </div>

            <div className="flex flex-col gap-3">
              {highestRiskAreas.map((area, idx) => (
                <div key={idx} className="p-3 bg-slate-50 border border-slate-100 rounded-lg flex justify-between items-center">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800">{area.zone}</h4>
                    <span className={`text-[10px] font-semibold block mt-0.5 ${
                      area.score.includes('High') ? 'text-red-600' : 'text-slate-500'
                    }`}>
                      {area.score}
                    </span>
                  </div>
                  <div className="text-right shrink-0">
                    <span className="text-lg font-extrabold text-slate-900 font-mono">{area.incidentsCount}</span>
                    <span className="text-[10px] text-slate-400 block uppercase">Violations</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
          
        </div>

      </div>
    </div>
  );
}
